# Generated by Django 3.2.5 on 2021-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_confirmcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmcode',
            name='valid_until',
            field=models.DateTimeField(null=True),
        ),
    ]
